<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Request 1</name>
   <tag></tag>
   <elementGuidId>d188a9f1-1e08-45f1-af91-3beaea86aa93</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>text/xml; charset=utf-8</value>
      <webElementGuid>1f485b4c-5522-4442-a15e-a693130fbb12</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.5.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <restRequestMethod></restRequestMethod>
   <restUrl></restUrl>
   <serviceType>SOAP</serviceType>
   <soapBody>&lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:tem=&quot;http://tempuri.org/&quot; xmlns:ban=&quot;http://schemas.datacontract.org/2004/07/BankOneAgent.Core.Implementations&quot; xmlns:arr=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;>
   &lt;soapenv:Header/>
   &lt;soapenv:Body>
      &lt;tem:RunTransaction>
         &lt;!--Optional:-->
         &lt;tem:transaction>
            &lt;ban:_x003C_AllFees_x003E_k__BackingField>?&lt;/ban:_x003C_AllFees_x003E_k__BackingField>
            &lt;ban:_x003C_Amount_x003E_k__BackingField>?&lt;/ban:_x003C_Amount_x003E_k__BackingField>
            &lt;ban:_x003C_AppzoneAccount_x003E_k__BackingField>?&lt;/ban:_x003C_AppzoneAccount_x003E_k__BackingField>
            &lt;ban:_x003C_ApzFee_x003E_k__BackingField>?&lt;/ban:_x003C_ApzFee_x003E_k__BackingField>
            &lt;ban:_x003C_ChannelCode_x003E_k__BackingField>?&lt;/ban:_x003C_ChannelCode_x003E_k__BackingField>
            &lt;ban:_x003C_CoreBankingSTAN_x003E_k__BackingField>?&lt;/ban:_x003C_CoreBankingSTAN_x003E_k__BackingField>
            &lt;ban:_x003C_Date_x003E_k__BackingField>?&lt;/ban:_x003C_Date_x003E_k__BackingField>
            &lt;ban:_x003C_DebitExpenseForFee_x003E_k__BackingField>?&lt;/ban:_x003C_DebitExpenseForFee_x003E_k__BackingField>
            &lt;ban:_x003C_DefaultGtw_x003E_k__BackingField>?&lt;/ban:_x003C_DefaultGtw_x003E_k__BackingField>
            &lt;ban:_x003C_Fee_x003E_k__BackingField>?&lt;/ban:_x003C_Fee_x003E_k__BackingField>
            &lt;ban:_x003C_GatewayFee_x003E_k__BackingField>?&lt;/ban:_x003C_GatewayFee_x003E_k__BackingField>
            &lt;ban:_x003C_ID_x003E_k__BackingField>?&lt;/ban:_x003C_ID_x003E_k__BackingField>
            &lt;ban:_x003C_ISWSTAN_x003E_k__BackingField>?&lt;/ban:_x003C_ISWSTAN_x003E_k__BackingField>
            &lt;ban:_x003C_Identifier_x003E_k__BackingField>?&lt;/ban:_x003C_Identifier_x003E_k__BackingField>
            &lt;ban:_x003C_InitialTransactionOriginalDataElements_x003E_k__BackingField>?&lt;/ban:_x003C_InitialTransactionOriginalDataElements_x003E_k__BackingField>
            &lt;ban:_x003C_InitiatingBranch_x003E_k__BackingField>?&lt;/ban:_x003C_InitiatingBranch_x003E_k__BackingField>
            &lt;ban:_x003C_InitiatorIPAddress_x003E_k__BackingField>?&lt;/ban:_x003C_InitiatorIPAddress_x003E_k__BackingField>
            &lt;ban:_x003C_InstitutionCode_x003E_k__BackingField>?&lt;/ban:_x003C_InstitutionCode_x003E_k__BackingField>
            &lt;ban:_x003C_IsDirectGatewayBilling_x003E_k__BackingField>?&lt;/ban:_x003C_IsDirectGatewayBilling_x003E_k__BackingField>
            &lt;ban:_x003C_IsFinalTrans_x003E_k__BackingField>?&lt;/ban:_x003C_IsFinalTrans_x003E_k__BackingField>
            &lt;ban:_x003C_IsLoggedForApproval_x003E_k__BackingField>?&lt;/ban:_x003C_IsLoggedForApproval_x003E_k__BackingField>
            &lt;ban:_x003C_IsMTO_x003E_k__BackingField>?&lt;/ban:_x003C_IsMTO_x003E_k__BackingField>
            &lt;ban:_x003C_IsMobileTrx_x003E_k__BackingField>?&lt;/ban:_x003C_IsMobileTrx_x003E_k__BackingField>
            &lt;ban:_x003C_IsRetakeFee_x003E_k__BackingField>?&lt;/ban:_x003C_IsRetakeFee_x003E_k__BackingField>
            &lt;ban:_x003C_IsSecondaryTrx_x003E_k__BackingField>?&lt;/ban:_x003C_IsSecondaryTrx_x003E_k__BackingField>
            &lt;ban:_x003C_IsWebServiceTrx_x003E_k__BackingField>?&lt;/ban:_x003C_IsWebServiceTrx_x003E_k__BackingField>
            &lt;ban:_x003C_IswFee_x003E_k__BackingField>?&lt;/ban:_x003C_IswFee_x003E_k__BackingField>
            &lt;ban:_x003C_MFB_x003E_k__BackingField>?&lt;/ban:_x003C_MFB_x003E_k__BackingField>
            &lt;ban:_x003C_MfbFee_x003E_k__BackingField>?&lt;/ban:_x003C_MfbFee_x003E_k__BackingField>
            &lt;ban:_x003C_NIPFee_x003E_k__BackingField>?&lt;/ban:_x003C_NIPFee_x003E_k__BackingField>
            &lt;ban:_x003C_NUBAN_x003E_k__BackingField>?&lt;/ban:_x003C_NUBAN_x003E_k__BackingField>
            &lt;ban:_x003C_Narration_x003E_k__BackingField>?&lt;/ban:_x003C_Narration_x003E_k__BackingField>
            &lt;ban:_x003C_OriginalTransactionID_x003E_k__BackingField>?&lt;/ban:_x003C_OriginalTransactionID_x003E_k__BackingField>
            &lt;ban:_x003C_PaidCustomerTransactionRoyaltyFee_x003E_k__BackingField>?&lt;/ban:_x003C_PaidCustomerTransactionRoyaltyFee_x003E_k__BackingField>
            &lt;ban:_x003C_PayerAccountNumber_x003E_k__BackingField>?&lt;/ban:_x003C_PayerAccountNumber_x003E_k__BackingField>
            &lt;ban:_x003C_PayerBank_x003E_k__BackingField>?&lt;/ban:_x003C_PayerBank_x003E_k__BackingField>
            &lt;ban:_x003C_Payer_x003E_k__BackingField>?&lt;/ban:_x003C_Payer_x003E_k__BackingField>
            &lt;ban:_x003C_PaymentReference_x003E_k__BackingField>?&lt;/ban:_x003C_PaymentReference_x003E_k__BackingField>
            &lt;ban:_x003C_PrintPageurl_x003E_k__BackingField>?&lt;/ban:_x003C_PrintPageurl_x003E_k__BackingField>
            &lt;ban:_x003C_ReceiverAccountNumber_x003E_k__BackingField>?&lt;/ban:_x003C_ReceiverAccountNumber_x003E_k__BackingField>
            &lt;ban:_x003C_ReceiverAccountType_x003E_k__BackingField>?&lt;/ban:_x003C_ReceiverAccountType_x003E_k__BackingField>
            &lt;ban:_x003C_ReceiverBVN_x003E_k__BackingField>?&lt;/ban:_x003C_ReceiverBVN_x003E_k__BackingField>
            &lt;ban:_x003C_ReceiverBankCode_x003E_k__BackingField>?&lt;/ban:_x003C_ReceiverBankCode_x003E_k__BackingField>
            &lt;ban:_x003C_ReceiverBank_x003E_k__BackingField>?&lt;/ban:_x003C_ReceiverBank_x003E_k__BackingField>
            &lt;ban:_x003C_ReceiverKYC_x003E_k__BackingField>?&lt;/ban:_x003C_ReceiverKYC_x003E_k__BackingField>
            &lt;ban:_x003C_ReceiverName_x003E_k__BackingField>?&lt;/ban:_x003C_ReceiverName_x003E_k__BackingField>
            &lt;ban:_x003C_ReceiverPhoneNumber_x003E_k__BackingField>?&lt;/ban:_x003C_ReceiverPhoneNumber_x003E_k__BackingField>
            &lt;ban:_x003C_ResponseCode_x003E_k__BackingField>?&lt;/ban:_x003C_ResponseCode_x003E_k__BackingField>
            &lt;ban:_x003C_SecondaryInstitutionCode_x003E_k__BackingField>?&lt;/ban:_x003C_SecondaryInstitutionCode_x003E_k__BackingField>
            &lt;ban:_x003C_SecondaryResponse_x003E_k__BackingField>?&lt;/ban:_x003C_SecondaryResponse_x003E_k__BackingField>
            &lt;ban:_x003C_SentToNIBSS_x003E_k__BackingField>?&lt;/ban:_x003C_SentToNIBSS_x003E_k__BackingField>
            &lt;ban:_x003C_SessionID_x003E_k__BackingField>?&lt;/ban:_x003C_SessionID_x003E_k__BackingField>
            &lt;ban:_x003C_StatusDescription_x003E_k__BackingField>?&lt;/ban:_x003C_StatusDescription_x003E_k__BackingField>
            &lt;ban:_x003C_StatusDetails_x003E_k__BackingField>?&lt;/ban:_x003C_StatusDetails_x003E_k__BackingField>
            &lt;ban:_x003C_Status_x003E_k__BackingField>?&lt;/ban:_x003C_Status_x003E_k__BackingField>
            &lt;ban:_x003C_TellerID_x003E_k__BackingField>?&lt;/ban:_x003C_TellerID_x003E_k__BackingField>
            &lt;ban:_x003C_TellerName_x003E_k__BackingField>?&lt;/ban:_x003C_TellerName_x003E_k__BackingField>
            &lt;ban:_x003C_TheGateway_x003E_k__BackingField>?&lt;/ban:_x003C_TheGateway_x003E_k__BackingField>
            &lt;ban:_x003C_ThirdPartyFee_x003E_k__BackingField>?&lt;/ban:_x003C_ThirdPartyFee_x003E_k__BackingField>
            &lt;ban:_x003C_ThirdPartyTransactionReference_x003E_k__BackingField>?&lt;/ban:_x003C_ThirdPartyTransactionReference_x003E_k__BackingField>
            &lt;ban:_x003C_TimeInitiated_x003E_k__BackingField>?&lt;/ban:_x003C_TimeInitiated_x003E_k__BackingField>
            &lt;ban:_x003C_TransactionReference_x003E_k__BackingField>?&lt;/ban:_x003C_TransactionReference_x003E_k__BackingField>
            &lt;ban:_x003C_TransferType_x003E_k__BackingField>?&lt;/ban:_x003C_TransferType_x003E_k__BackingField>
            &lt;ban:_x003C_UseThirdPartyFee_x003E_k__BackingField>?&lt;/ban:_x003C_UseThirdPartyFee_x003E_k__BackingField>
            &lt;ban:_x003C_VAT_x003E_k__BackingField>?&lt;/ban:_x003C_VAT_x003E_k__BackingField>
            &lt;ban:_x003C__TransactionServiceCode_x003E_k__BackingField>
               &lt;!--Zero or more repetitions:-->
               &lt;arr:anyType>?&lt;/arr:anyType>
            &lt;/ban:_x003C__TransactionServiceCode_x003E_k__BackingField>
         &lt;/tem:transaction>
      &lt;/tem:RunTransaction>
   &lt;/soapenv:Body>
&lt;/soapenv:Envelope></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod>SOAP</soapRequestMethod>
   <soapServiceEndpoint>http://10.1.4.13/BankOneAgent/Services/TransferService.svc</soapServiceEndpoint>
   <soapServiceFunction>RunTransaction</soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>false</useServiceInfoFromWsdl>
   <wsdlAddress>http://10.1.4.13/BankOneAgent/Services/TransferService.svc?wsdl</wsdlAddress>
</WebServiceRequestEntity>
