jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-report
          path: cypress/reports
