<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Request 1</name>
   <tag></tag>
   <elementGuidId>cd54a1db-3008-4cfb-8413-678a503c23ce</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>text/xml; charset=utf-8</value>
      <webElementGuid>ce607796-5897-47b0-946b-dad334015b56</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.5.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <restRequestMethod></restRequestMethod>
   <restUrl></restUrl>
   <serviceType>SOAP</serviceType>
   <soapBody>&lt;soapenv:Envelope xmlns:soapenv=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:tem=&quot;http://tempuri.org/&quot;>
   &lt;soapenv:Header/>
   &lt;soapenv:Body>
      &lt;tem:DoBillsPaymentTransaction>
         &lt;!--Optional:-->
         &lt;tem:billerID>?&lt;/tem:billerID>
         &lt;!--Optional:-->
         &lt;tem:billerName>?&lt;/tem:billerName>
         &lt;!--Optional:-->
         &lt;tem:billerCategoryID>?&lt;/tem:billerCategoryID>
         &lt;!--Optional:-->
         &lt;tem:billerCategoryName>?&lt;/tem:billerCategoryName>
         &lt;!--Optional:-->
         &lt;tem:paymentItemID>?&lt;/tem:paymentItemID>
         &lt;!--Optional:-->
         &lt;tem:PaymentItemCode>?&lt;/tem:PaymentItemCode>
         &lt;!--Optional:-->
         &lt;tem:PaymentItemName>?&lt;/tem:PaymentItemName>
         &lt;!--Optional:-->
         &lt;tem:CustomerID>?&lt;/tem:CustomerID>
         &lt;!--Optional:-->
         &lt;tem:CustomerDepositSlipNumber>?&lt;/tem:CustomerDepositSlipNumber>
         &lt;!--Optional:-->
         &lt;tem:CustomerName>?&lt;/tem:CustomerName>
         &lt;!--Optional:-->
         &lt;tem:AccountNumber>?&lt;/tem:AccountNumber>
         &lt;!--Optional:-->
         &lt;tem:CustomerEmail>?&lt;/tem:CustomerEmail>
         &lt;!--Optional:-->
         &lt;tem:CustomerPhone>?&lt;/tem:CustomerPhone>
         &lt;!--Optional:-->
         &lt;tem:Amount>?&lt;/tem:Amount>
         &lt;!--Optional:-->
         &lt;tem:institutionCode>?&lt;/tem:institutionCode>
         &lt;!--Optional:-->
         &lt;tem:referenceNumber>?&lt;/tem:referenceNumber>
         &lt;!--Optional:-->
         &lt;tem:isDirectGatewayBilling>?&lt;/tem:isDirectGatewayBilling>
         &lt;!--Optional:-->
         &lt;tem:appzoneAccount>?&lt;/tem:appzoneAccount>
      &lt;/tem:DoBillsPaymentTransaction>
   &lt;/soapenv:Body>
&lt;/soapenv:Envelope></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod>SOAP</soapRequestMethod>
   <soapServiceEndpoint>http://10.1.4.13/BankOneAgent/Services/TransferService.svc</soapServiceEndpoint>
   <soapServiceFunction>DoBillsPaymentTransaction</soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>false</useServiceInfoFromWsdl>
   <wsdlAddress>http://10.1.4.13/BankOneAgent/Services/TransferService.svc?wsdl</wsdlAddress>
</WebServiceRequestEntity>
